spring.application.name=login
server.port=8080
logging.level.org.springframework.security=DEBUG

# Datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL Init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}
application.security.jwt.refresh-token=${JWT_REFRESH_TOKEN}